version: 0.1

phases:
     pre_build:
          commands:
          - $(aws ecr get-login)
          - TAG="latest"
     build:
          commands:
          - docker build -t cicdtestreop .
          - docker tag cicdtestrepo:latest 897561443003.dkr.ecr.us-east-2.amazonaws.com/cicdtestrepo:latest
     post_build:
          commands:
          - docker push 897561443003.dkr.ecr.us-east-2.amazonaws.com/cicdtestrepo:latest
          - printf '{"Image":"%s:%s"}' "cicdtestreop" "latest" > build.json
artifacts:
     files:
     - build.json
     - cfn/service.yml
     - cfn/environments/production.json
     discard-paths: yes
